# fly.toml app configuration file generated for backend-nameless-silence-5442 on 2025-01-02T16:33:40+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-nameless-silence-5442'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
